### PR TITLE
support arm64

### PR DESCRIPTION
**Pull request by jievince**

### CODE REVIEW

**Comment by Shylock-Hg** [comment]
And the action provide various machine (windows, linux, intel, arm), so you could run the binary in ci.

**Comment by jievince** [comment]
> I see this
> 
> ```
> The feature was introduced in GO 1.5. Don’t expect it to work on earlier versions.
> Everything works fine until you start using cgo. Cgo requires a c compiler and cross-compiling C is not trivial. If cross-compilation is important to you stay away from libraries using cgo.
> ```
> 
> in one article.
> Plz check this.

I think we can disable cgo via `CGO_ENABLED=0` when build nebula-console

**Comment by jievince** [comment]
> Go creates static binaries by default unless you use cgo to call C code, in which case it will create a dynamically linked library. 

> w/ netgo  w/o netgo
> CGO_ENABLED=0   builtin   builtin
> CGO_ENABLED=1   builtin   external
> builtin: use netgo resolver, external: use cgo resolver

**Review by Aiee — APPROVED** [review]
LGTM.

**Pull request merged**
