### PR TITLE
Support the tck format for the output of EXPLAIN

### PR DESCRIPTION
**Pull request by AntiTopQuark**
## What type of PR is this?
- [ ] bug
- [x] feature
- [ ] enhancement

#### Issue(s) number: 
https://github.com/vesoft-inc/nebula/issues/5274

#### Description:
rt, Support the tck format for the output of EXPLAIN

## How do you solve it?
Modify the style of `pretty/table`  to produce results in the TCK format.

## Special notes for your reviewer, ex. impact of this fix, design document, etc:
related link:
- the pr link of nebula repo: https://github.com/vesoft-inc/nebula/pull/5414
- the pr link of nebula-console: https://github.com/vesoft-inc/nebula-console/pull/210
- the pr link of nebula nebula-go:https://github.com/vesoft-inc/nebula-go/pull/265
- the pr link of nebula-doc:https://github.com/vesoft-inc/nebula-docs/pull/2017
- the pr link of nebula-doc-cn:https://github.com/vesoft-inc/nebula-docs-cn/pull/2664

### CODE REVIEW

**Comment by xtcyclist** [comment]
Hi. There are some build errors. Please address them.

**Comment by AntiTopQuark** [comment]
> Hi. There are some build errors. Please address them.

Hello, the reason for the building failure is due to the missing function called 'MakePlanByTck' in the dependent 'nebula-go' library. 
I have already implemented this function and submitted a PR: https://github.com/vesoft-inc/nebula-go/pull/265
Therefore, it might be necessary to first merge the PR for the 'nebula-go' library before the current repository (nebula-console) can be successfully compiled.

**Comment by Sophie-Xie** [comment]
> > Hi. There are some build errors. Please address them.
> 
> Hello, the reason for the building failure is due to the missing function called 'MakePlanByTck' in the dependent 'nebula-go' library. I have already implemented this function and submitted a PR: [vesoft-inc/nebula-go#265](https://github.com/vesoft-inc/nebula-go/pull/265) Therefore, it might be necessary to first merge the PR for the 'nebula-go' library before the current repository (nebula-console) can be successfully compiled.

vesoft-inc/nebula-go#265 merged and nebula-console updated the dependent. But we can't rebase your pr, pls rebase it and try the CI, thanks.

**Review by jievince — APPROVED** [review]
LGTM

**Pull request merged**
