### PR TITLE
enable tck mode

### PR DESCRIPTION
**Pull request by jievince**
```
Now we can wrap multi line queries in three quotes(""" or ''')
(root@nebula) [nba]>       """
                  ->       MATCH (v:player)
                  ->       WHERE v.age >= 38 AND v.age < 45
                  ->       RETURN v.name AS Name, v.age AS Age
                  ->       """
+-----------------+-----+
| Name            | Age |
+-----------------+-----+
| "Manu Ginobili" | 41  |
+-----------------+-----+
| "Dirk Nowitzki" | 40  |
```

### CODE REVIEW

**Comment by Shylock-Hg** [comment]
What's the purpose?

**Comment by jievince** [comment]
> What's the purpose?

Make it easy to copy multi-line queries that enclosed by three quotes in tck test in console.

**Comment by Shylock-Hg** [comment]
> > What's the purpose?
> 
> Make it easy to copy multi-line queries that enclosed by three quotes in tck test to console.

In fact, I think you could copy-and-paste without the three quotes directly.

**Comment by Amber1990Zhang** [comment]
> > > What's the purpose?
> > 
> > 
> > Make it easy to copy multi-line queries that enclosed by three quotes in tck test to console.
> 
> In fact, I think you could copy-and-paste without the three quotes directly.

yes I can't agree more

**Comment by jievince** [comment]
> > > What's the purpose?
> > 
> > 
> > Make it easy to copy multi-line queries that enclosed by three quotes in tck test to console.
> 
> In fact, I think you could copy-and-paste without the three quotes directly.



> > > > What's the purpose?
> > > 
> > > 
> > > Make it easy to copy multi-line queries that enclosed by three quotes in tck test to console.
> > 
> > 
> > In fact, I think you could copy-and-paste without the three quotes directly.
> 
> yes I can't agree more

If I can do it, I will. But I can't.
For example:
```
MATCH (v:player) 
WHERE v.age >= 38 AND v.age < 45
RETURN v.name AS Name, v.age AS Age
```
For these 3 lines query, each line has a `carriage return` symbol at the end of the line. But the first and second line's `carriage return` means the “this query has not been entered completely, continue to splice the content of the next line”. However, the third line's `carriage return` means "this query has entered completely, please send them to server". 
I couldn't distinguish them in coding.

**Comment by Shylock-Hg** [comment]
> > > > What's the purpose?
> > > 
> > > 
> > > Make it easy to copy multi-line queries that enclosed by three quotes in tck test to console.
> > 
> > 
> > In fact, I think you could copy-and-paste without the three quotes directly.
> 
> > > > > What's the purpose?
> > > > 
> > > > 
> > > > Make it easy to copy multi-line queries that enclosed by three quotes in tck test to console.
> > > 
> > > 
> > > In fact, I think you could copy-and-paste without the three quotes directly.
> > 
> > 
> > yes I can't agree more
> 
> If I can do it, I will. But I can't.
> For example:
> 
> ```
> MATCH (v:player) 
> WHERE v.age >= 38 AND v.age < 45
> RETURN v.name AS Name, v.age AS Age
> ```
> 
> For these 3 lines query, each line has a `carriage return` symbol at the end of the line. But the first and second line's `carriage return` means the “this query has not been entered completely, continue to splice the content of the next line”. However, the third line's `carriage return` means "this query has entered completely, please send them to server".
> I couldn't distinguish them in coding.

Ok, got it.

**Review by Aiee — APPROVED** [review]

**Pull request merged**
