### PR TITLE
add go-prompt

### PR DESCRIPTION
**Pull request by HarrisChu**
add go-prompt, need improvement as below:
1. ctrl+r , search in history.
2. write history to writer interface
3. add an error when type ctrl+d in `Input()`

https://user-images.githubusercontent.com/1726587/141711596-4d09e150-33c5-4896-970d-c2308090df9c.mov

### CODE REVIEW

**Comment by jievince** [comment]
Well done! Keep working

**Comment by jievince** [comment]
Doesn't it work well in docker?

**Comment by HarrisChu** [comment]
> Doesn't it work well in docker?

Yes

**Comment by jievince** [comment]
It's ok to me. The history-related functions of go-prompt could be done in another PR.

**Review by jievince — APPROVED** [review]

**Pull request merged**
